Parameters:
  myRDSjdbcstring:
    Description: My database
    Type: String
  myRDSUsername:
    Description: Username for database access
    Type: String
    NoEcho: true
  myRDSPassword:
    Description: Username for database access
    Type: String
    NoEcho: true
  myRDSCreateTableSql:
    Default: "CREATE TABLE IF NOT EXISTS persons (\n  id INTEGER,\n  email VARCHAR(100),\n  billing_state VARCHAR(3),\n  billing_postal INTEGER,\n  billing_address VARCHAR(255),\n  PRIMARY KEY (id)\n);"
    Description: Password database access
    Type: String
  myInputS3Loc:
    Default: "s3://s3-eventbridge-batch"
    Description: Path to s3 bucket
    Type: String
  myRDSTableName:
    Default: persons
    Description: Password database access
    Type: String
  SecurityGroupID:
    Default: sg-0afdf2d5ce4c8ed3e
    Description: Security group id for ec2 instance
    Type: String
Resources:
    S3InputRDSOutput:
      Type: AWS::DataPipeline::Pipeline
      Properties:
        Name: S3InputRDSPostgresOutput
        Description: "Pipeline to copy S3 data to RDS DB"
        Activate: true
        ParameterObjects:
          -
            Id: "*myRDSPassword"
            Attributes:
              -
                Key: "description"
                StringValue: "RDS Password"
              -
                Key: "type"
                StringValue: "String"
          -
            Id: "*myRDSUsername"
            Attributes:
              -
                Key: "description"
                StringValue: "RDS Username"
              -
                Key: "type"
                StringValue: "String"
          -
            Id: "myRDSjdbcstring"
            Attributes:
            -
              Key: "description"
              StringValue: "RDS Postgres jdbc string"
            -
              Key: "type"
              StringValue: "String"
          -
            Id: "myRDSjdbcDriverJarUri"
            Attributes:
            -
                Key: "description"
                StringValue: "jdbc driver uri"
            -
                Key: "type"
                StringValue: "String"
          -
            Id: "myRDSjdbcDriverClass"
            Attributes:
             -
                Key: "description"
                StringValue: "jdbc driver uri"
             -
                Key: "type"
                StringValue: "String"
          -
            Id: "myInputS3Loc"
            Attributes:
            -
                Key: "description"
                StringValue: "Path to s3 bucket"
            -
                Key: "type"
                StringValue: "String"
          -
            Id: "myRDSTableName"
            Attributes:
            -
                Key: "description"
                StringValue: "RDS Table name"
            -
                Key: "type"
                StringValue: "String"
          -
            Id: "myRDSCreateTableSql"
            Attributes:
            -
                Key: "description"
                StringValue: "Create table sql query"
            -
                Key: "type"
                StringValue: "String"
        ParameterValues:
          -
            Id: "*myRDSUsername"
            StringValue: !Ref myRDSUsername
          -
            Id: "*myRDSPassword"
            StringValue: !Ref myRDSPassword
          -
            Id: "myRDSjdbcstring"
            StringValue: !Ref myRDSjdbcstring
          -
            Id: "myInputS3Loc"
            StringValue: !Ref myInputS3Loc
          -
            Id: "myRDSTableName"
            StringValue: !Ref myRDSTableName
          -
            Id: "myRDSCreateTableSql"
            StringValue: !Ref myRDSCreateTableSql
          -
            Id: "myRDSjdbcDriverJarUri"
            StringValue: "s3://datapipeline-us-east-1/us-east-1/software/latest/TaskRunner/Postgres-jdbc.jar"
          -
            Id: "myRDSjdbcDriverClass"
            StringValue: "org.postgresql.Driver"
        PipelineObjects:
          -
            Id: "RDSPostgres"
            Name: "RDSPostgres"
            Fields:
              -
                Key: "type"
                StringValue: "JdbcDatabase"
              -
                Key: "connectionString"
                StringValue:  "#{myRDSjdbcstring}"
              -
                Key: "jdbcDriverClass"
                StringValue: "#{myRDSjdbcDriverClass}"
              -
                Key: "jdbcDriverJarUri"
                StringValue: "#{myRDSjdbcDriverJarUri}"
              -
                Key: "username"
                StringValue: "#{*myRDSUsername}"
              -
                Key: "*password"
                StringValue: "#{*myRDSPassword}"
          -
            Id: "CopyS3DatatoEC2"
            Name: "CopyS3DatatoEC2"
            Fields:
              -
                Key: "type"
                StringValue: "ShellCommandActivity"
              -
                Key: "runsOn"
                RefValue: "Ec2Instance"
              -
                Key: "command"
                StringValue: "(sudo yum -y update aws-cli) && (aws s3 cp #{myInputS3Loc}/ /home/ec2-user/ --recursive)"
          -
            Id: "CopyDatatoRDS"
            Name: "CopyDatatoRDS"
            Fields:
              -
                Key: "type"
                StringValue: "ShellCommandActivity"
              -
                Key: "runsOn"
                RefValue: "Ec2Instance"
              -
                Key: "dependsOn"
                RefValue: "CopyS3DatatoEC2"
              -
                Key: "dependsOn"
                RefValue: "RdsPostgresTableCreateActivity"
              -
                Key: "scriptUri"
                StringValue: "#{myInputS3Loc}/psql-copy-s3-rds.sh"
              -
                Key: "scriptArgument"
                StringValue: "--red_jdbc=#{myRDSjdbcstring}"
              -
                Key: "scriptArgument"
                StringValue: "--red_usr=#{*myRDSUsername}"
              -
                Key: "scriptArgument"
                StringValue: "--red_pwd=#{*myRDSPassword}"
              -
                Key: "scriptArgument"
                StringValue: "--red_tbl=#{myRDSTableName}"
          -
            Id: "RdsPostgresTableCreateActivity"
            Name: "RdsPostgresTableCreateActivity"
            Fields:
              -
                Key: "type"
                StringValue: "SqlActivity"
              -
                Key: "database"
                RefValue: "RDSPostgres"
              -
                Key: "runsOn"
                RefValue: "Ec2Instance"
              -
                Key: "script"
                StringValue: "#{myRDSCreateTableSql}"
          -
            Id: "Ec2Instance"
            Name: "Ec2Instance"
            Fields:
              -
                Key: "type"
                StringValue: "Ec2Resource"
              -
                Key: "instanceType"
                StringValue: "t1.micro"
              -
                Key: "terminateAfter"
                StringValue: "30 minutes"
              -
                Key: "imageId"
                StringValue: "ami-0022f774911c1d690"
              - Key: "actionOnTaskFailure"
                StringValue: "terminate"
              - Key: "securityGroupIds"
                StringValue: !Ref SecurityGroupID
              - Key: "maximumRetries"
                StringValue: "1"
          -
            Id: "Default"
            Name: "Default"
            Fields:
              -
                Key: "type"
                StringValue: "Default"
              -
                Key: "failureAndRerunMode"
                StringValue: "CASCADE"
              -
                Key: "resourceRole"
                StringValue: "ec2-profile"
              -
                Key: "role"
                StringValue: "DataPipelineDefaultRole"
              -
                Key: "pipelineLogUri"
                StringValue: "s3://data-pipeline-logs1/logs/"
              -
                Key: "scheduleType"
                StringValue: "ONDEMAND"
              -
                Key: "maxActiveInstances"
                StringValue: "2"
