Parameters:
  State:
    Default: "ENABLED"
    Description: Default State when EventBridge Rule is created
    Type: String
    ConstraintDescription: State must have values either 'ENABLED' or 'DISABLED'
    AllowedValues:
      - "ENABLED"
      - "DISABLED"
  EventBusName:
    Default: ''
    Description: Name of new eventbus to create.
    Type: String
Conditions:
  CreateBusResource: !Not
    - !Equals
        - !Ref EventBusName
        - ''
Resources:
  EventBusResource:
    Type: 'AWS::Events::EventBus'
    Condition: CreateBusResource
    Properties:
      Name: !Ref EventBusName
  EC2EventstoSQS:
    Type: 'AWS::Events::Rule'
    Properties:
      Description:  send all EC2 events to an SQS queue and include DLQ
      Name: EC2EventstoSQS
      EventPattern:
        source:
          - aws.ec2
      State: !Ref State
      Targets:
        - Arn:
            Fn::ImportValue: SQS-etl
          Id: 'SQLETLQueue'
          RetryPolicy:
            MaximumRetryAttempts: 4
            MaximumEventAgeInSeconds: 400
          DeadLetterConfig:
            Arn:
              Fn::ImportValue: SQS-DLQ
  EventBridgeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
         Fn::ImportValue: LambdaRDSOnOff-Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !Sub "arn:aws:events:us-east-1:${AWS::AccountId}:rule/*"