Parameters:
  S3DataPath:
    Default: "s3://flight-delays-2008/delays/"
    Description: s3 path to data
    Type: String
  SparkScriptLocation:
    Default: "s3://flight-delays-2008/script.py"
    Description: s3 path to glue script
    Type: String
  AthenaQueryOutputPath:
    Default: "s3://aws-athena-query-results-us-east-1-376337229415"
    Type: String
  StateMachineDefinitionBucket:
    Default: "flight-delays-2008"
    Type: String
  StateMachineDefinitionKey:
    Default: "glue_athena_sf.json"
    Type: String
Resources:
  GlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Role:
         Fn::ImportValue: RoleGlue-Arn
      Description: crawler config
      Targets:
        S3Targets:
          - Path: !Ref S3DataPath
      DatabaseName: default
      Name: demo-crawler
      Configuration: "{\"Version\":1.0,\"CrawlerOutput\":{\"Partitions\":{\"AddOrUpdateBehavior\":\"InheritFromTable\"},\"Tables\":{\"AddOrUpdateBehavior\":\"MergeNewColumns\"}}}"
  DemoGlueJob:
      Type: AWS::Glue::Job
      Properties:
        Command:
          Name: glueetl
          ScriptLocation: !Ref SparkScriptLocation
        DefaultArguments:
          "--job-bookmark-option": "job-bookmark-disable"
        ExecutionProperty:
          MaxConcurrentRuns: 2
        GlueVersion: "3.0"
        NumberOfWorkers: 5
        WorkerType: "Standard"
        Timeout: 6
        MaxRetries: 0
        Name: demo-glue-etl-job
        Role:
          Fn::ImportValue: RoleGlue-Arn
  MyStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: s3-glue-athena
      DefinitionS3Location:
        Bucket: !Ref StateMachineDefinitionBucket
        Key: !Ref StateMachineDefinitionKey
      DefinitionSubstitutions:
        SNSTopicArn:
          Fn::ImportValue: SNSTopics-etl
        JobName: !Ref DemoGlueJob
        CrawlerName: !Ref GlueCrawler
        AthenaOutputPath: !Ref AthenaQueryOutputPath
      RoleArn:
        Fn::ImportValue: RoleStepFunctions-GlueArn
    DependsOn:
      - "DemoGlueJob"
      - "GlueCrawler"
