AWSTemplateFormatVersion: 2010-09-09
Resources:
  DDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: title
          AttributeType: S
        - AttributeName: year
          AttributeType: 'N'
      KeySchema:
        - AttributeName: year
          KeyType: HASH
        - AttributeName: title
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
      TableName: "movies"
  SNSSubscriptionQueue:
    Type: 'AWS::SNS::Subscription'
    Properties:
      TopicArn:
        Fn::ImportValue: SNSTopics-etl
      Endpoint:
        Fn::ImportValue: SQS-etl
      Protocol: sqs
      RawMessageDelivery: 'true'
  batchwrites3dynamo:
    Type: 'AWS::Lambda::Function'
    DeletionPolicy: "Retain"
    Properties:
      FunctionName: "batch_write_s3_dynamodb"
      Handler: index.lambda_handler
      Role:
        Fn::ImportValue: S3DynamoArn
      Architectures:
        - x86_64
      Runtime: python3.9
      Timeout: 300
      MemorySize: 1024
      Code:
        S3Bucket: lambda-zip-for-cf
        S3Key: batch_write_s3_dynamodb.zip
    DependsOn:
      - "DDBTable"
  ddbinputtransform:
    Type: 'AWS::Lambda::Function'
    DeletionPolicy: "Retain"
    Properties:
      FunctionName: "ddb_input_transform"
      Handler: index.lambda_handler
      Role:
        Fn::ImportValue: S3DynamoArn
      Architectures:
        - x86_64
      Runtime: python3.9
      Timeout: 40
      MemorySize: 1024
      Code:
        S3Bucket: lambda-zip-for-cf
        S3Key: ddb_input_transform.zip
    DependsOn:
      - "DDBTable"

