AWSTemplateFormatVersion: 2010-09-09
Resources:
  DDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: title
          AttributeType: S
        - AttributeName: year
          AttributeType: 'N'
      KeySchema:
        - AttributeName: year
          KeyType: HASH
        - AttributeName: title
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
      TableName: "movies"
  SNSSubscriptionQueue:
    Type: 'AWS::SNS::Subscription'
    Properties:
      TopicArn:
        Fn::ImportValue: SNSTopics-etl
      Endpoint:
        Fn::ImportValue: SQS-etl
      Protocol: sqs
      RawMessageDelivery: 'true'