AWSTemplateFormatVersion: 2010-09-09
Parameters:
  LambdaImageUri:
    Description: ECR image URI
    Type: String
  LambdaZipBucket:
    Default: "tweets-lambda-image"
    Description: S3 Bucket where the zip for firehose lambda is stored
    Type: String
  LambdaZipS3Key:
    Default: "transform-firehouse-b64-json.zip"
    Description: The Amazon S3 key of the deployment package.
    Type: String
  DestBucketArn:
    Default: "arn:aws:s3:::kinesis-firehose-twitter-output"
    Description: Arn for destination bucket to output from firehose
    Type: String
Resources:
  KinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: TwitterStream
      ShardCount: 3
    DependsOn:
      - "TweetsStreamImage"
  Deliverystream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: TweetsDeliveryFirehose
      DeliveryStreamType: KinesisStreamAsSource
      KinesisStreamSourceConfiguration:
        KinesisStreamARN: !GetAtt KinesisStream.Arn
        RoleARN:
          Fn::ImportValue: RoleKinesis-FirehoseArn
      ExtendedS3DestinationConfiguration:
        BucketARN: !Ref DestBucketArn
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 50
        CompressionFormat: UNCOMPRESSED
        Prefix: firehose/
        RoleARN:
          Fn::ImportValue: RoleKinesis-FirehoseArn
        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: "deliverystream"
          LogStreamName: "s3Backup"
        ProcessingConfiguration:
          Enabled: true
          Processors:
            - Type: "Lambda"
              Parameters:
              - ParameterName: "LambdaArn"
                ParameterValue: !GetAtt FirehoseLambda.Arn
    DependsOn:
      - "KinesisStream"
      - "FirehoseLambda"
  TweetsStreamImage:
    Type: 'AWS::Lambda::Function'
    Properties:
      PackageType: Image
      FunctionName: "TweetsStreamImage"
      Code:
        ImageUri: !Ref 'LambdaImageUri'
      Role:
        Fn::ImportValue: RoleLambdaImage-TwitterArn
      Timeout: 300
      MemorySize: 1024
  FirehoseLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: "transform-firehouse-b64-json"
      Handler: index.lambda_handler
      Role:
        Fn::ImportValue: FirehoseNLPArn
      Architectures:
        - x86_64
      Runtime: python3.9
      Timeout: 300
      MemorySize: 1024
      Code:
        S3Bucket: !Ref LambdaZipBucket
        S3Key: !Ref LambdaZipS3Key
